apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
  claimRef:
      namespace: default
      name: influxdb-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
  labels:
    app: influxdb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 750Mi
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
  labels:
    app: influxdb
spec:
  type: ClusterIP
  ports:
  - port: 8086
    name: influxdb
    targetPort: 8086
  - name: telegraf-docker
    port: 8125
    protocol: TCP
    targetPort: 8125
  selector:
    app: influxdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deploy
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      restartPolicy: Always
      containers:
      - name: influxdb
        image: img_influxdb
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - rc-service influxdb status || exit 1; rc-service telegraf status || exit 1;
          initialDelaySeconds: 10
          periodSeconds: 5
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
        - containerPort: 8125
        volumeMounts:
            - mountPath: /var/lib/influxdb
              name: influxdb-persistent-storage
            - mountPath: "/var/run/docker.sock"
              name: influxdb-endpoint
      volumes:
        - name: influxdb-persistent-storage
          persistentVolumeClaim:
            claimName: influxdb-pv-claim
        - name: influxdb-endpoint
          hostPath:
            path: /var/run/docker.sock
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: influxdb
  labels:
    app: influxdb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: influxdb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
