apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  labels:
    app: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: ip-pools
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    name: phpmyadmin
    targetPort: 5000
  selector:
    app: phpmyadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deploy
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      restartPolicy: Always
      containers:
      - name: phpmyadmin
        image: img_pma
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - rc-service nginx status || exit 1; ps -o user,comm,args | egrep -i "^root[ ]*php-fpm7.*\.conf" || exit 1;
          initialDelaySeconds: 10
          periodSeconds: 5
        imagePullPolicy: Never
        ports:
        - containerPort: 5000