apiVersion: 1
datasources:
  - name: InfluxDB_Container_Services
    type: influxdb
    access: proxy
    url: http://influxdb-svc.default.svc.cluster.local:8086
    database: "metrics"
    basicAuth: true
    basicAuthUser: user
    basicAuthPassword: password
    editable: true
